### ISSUE TITLE
Request for release

### ISSUE THREAD

**Issue by realtime-neil** [DENSORobot/orin_bcap#4]
As of this writing, `orin_bcap` has no "official" release, tagged or otherwise.

Please consider this issue my request for an official tagged release, preferably one with a "dotted-triplet" version string like those documented here: https://semver.org/

Thanks in advance.

**Comment by realtime-neil** [comment]
Might I suggest the following:

```
$ git tag -s -m "orin_bcap release 1.0.0" 1.0.0
$ git push --tags
```

**Comment by furukawahiromi** [comment]
Thank you for your suggestion.
I have pushed the tag.

**Comment by realtime-neil** [comment]
@furukawahiromi I can see it:

https://github.com/DENSORobot/orin_bcap/releases/tag/v1.0.0

Thank you very much!
